name: GHAction

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

jobs:
  ci_step:
    name: Build, tag and push Docker image to DockerHub and GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Check out the source_repo
        uses: actions/checkout@v4

      - name: Docker metadata definitions
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/zad2
          flavor: latest=false
          tags: |
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}

      - name: QEMU set-up
        uses: docker/setup-qemu-action@v3

      - name: Buildx set-up
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: |
            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/zad2:cache
          cache-to: |
            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/zad2:cache
          tags: ${{ steps.meta.outputs.tags }}

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan Docker image for vulnerabilities
        id: trivy
        run: |
          trivy image --severity HIGH,CRITICAL --exit-code 1 ${{ vars.DOCKERHUB_USERNAME }}/zad2:$(echo ${{ steps.meta.outputs.tags }} | cut -d',' -f1)
      
      - name: Login to GitHub Container Registry
        if: success()  # Only run if the previous step was successful
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GitHub Container Registry
        if: success()  # Only run if the previous step was successful
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: |
            type=registry,ref=ghcr.io/${{ github.repository }}/zad2:cache
          cache-to: |
            type=registry,ref=ghcr.io/${{ github.repository }}/zad2:cache
          tags: ghcr.io/${{ github.repository }}/zad2:${{ steps.meta.outputs.tags }}
